version: "3.8"

services:
  ts-django-blue:
    build:
      context: .
    container_name: test-dev-blue
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      - PORTS=8000
      - DJANGO_CONFIGURATION=production
    command:
      - /bin/sh
      - -c
      - |
        dockerize -wait tcp://ts-postgres:5432 -timeout 20s
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate
        poetry run gunicorn -c gunicorn.conf.py -b 0.0.0.0:8000 app.core.asgi:application
    networks:
      - test-network
    volumes:
      - ./save:/workdir/save

networks:
  test-network:
    external: true
    name: test-network
    driver: bridge